#!/usr/bin/perl

use strict;
use warnings;
use lib ".";

use Data::Dumper;
use BaconBird::Controller;
use BaconBird::Model;
use BaconBird::View;
use BaconBird::Shortener;
use BaconBird::KeyMap;

my $ctrl = BaconBird::Controller->new({ keymap => BaconBird::KeyMap->new, shortener => BaconBird::Shortener->new });

$ctrl->model(BaconBird::Model->new(ctrl => $ctrl));
$ctrl->view(BaconBird::View->new(ctrl => $ctrl));

$ctrl->run;

