#!/usr/bin/perl -w

use strict;
#use lib "/usr/share/baconbird";

use Net::Twitter;
use stfl;
use Data::Dumper;

my $version = "0.1";

sub load_tokens($);
sub save_tokens($$$);
sub format_timeline($);

my $configdir = $ENV{'HOME'} . "/.baconbird";
my $pinfile = $configdir . "/authcode";

my $consumer_key = "HNWGxf3exkB1mQGpM83PWw";
my $consumer_secret = "dcQsVwycEa6vNCMO0ljbzZfzloqBXcRDMYXRo1bsN7k";

mkdir($configdir, 0755);

my $nt = Net::Twitter->new(
	traits	=> [qw/OAuth API::REST InflateObjects/],
	consumer_key	=> $consumer_key,
	consumer_secret	=> $consumer_secret,
);

my ($access_token, $access_token_secret) = load_tokens($pinfile);
if ($access_token && $access_token_secret) {
	$nt->access_token($access_token);
	$nt->access_token_secret($access_token_secret);
}

my ($user_id, $screen_name);

unless ($nt->authorized) {
	print "Authorize this app at ", $nt->get_authorization_url, " and enter the PIN#\n";
	my $pin = <STDIN>;
	chomp($pin);

	($access_token, $access_token_secret, $user_id, $screen_name) = $nt->request_access_token(verifier => $pin);
	save_tokens($pinfile, $access_token, $access_token_secret);
}

my $f = stfl::create( <<EOT );
vbox
  hbox
    .expand:0
    \@style_normal:bg=blue,fg=white,attr=bold
    label text:"[baconbird $version]" .expand:h
    label .tie:r text[rateinfo]:"-1/-1" .expand:0
  list[tweets]
    style_focus[listfocus]:fg=yellow,bg=blue,attr=bold
    .expand:vh
    pos_name[tweetposname]:
    pos[tweetpos]:0
  vbox
    .expand:0
    .display:1
    label text:"q:Quit ... more help" .expand:h style_normal:bg=blue,fg=white,attr=bold
  hbox[lastline]
    .expand:0
    label text[msg]:"foobar" .expand:h
EOT

$f->set("msg", "Loading home timeline...");
$f->run(-1);
my $timeline_list = format_timeline($nt->home_timeline({ count => 10 }));
$f->modify("tweets", "replace_inner", $timeline_list);
$f->set("msg", "");

INPUT_LOOP: 
for (;;) {
	my $e = $f->run(0);

	if ($e) {
		if ($e eq "q") {
			last INPUT_LOOP;
		} else {
			$f->set("msg", "input: $e");
		}
	}
}

#print Dumper($nt->home_timeline({ count => 10 }));
#foreach my $tweet (@{$nt->home_timeline({ count => 10 })}) {
#	print "[@", $tweet->{user}{screen_name}, "] ", $tweet->{text}, "\n";
#}

sub load_tokens($) {
	my $pinfile = shift;
	open(my $fh, "<", $pinfile) or return (undef, undef);
	my $access_token = <$fh>;
	chomp($access_token);
	my $access_token_secret = <$fh>;
	chomp($access_token_secret);
	close($fh);
	return ($access_token, $access_token_secret);
}

sub save_tokens($$$) {
	my ($pinfile, $access_token, $access_token_secret) = @_;
	open(my $fh,">",$pinfile) or die "Error: couldn't open $pinfile: $!\n";
	print $fh "$access_token\n$access_token_secret\n";
	close($fh);
}

sub format_timeline($) {
	my $tl = shift;
	my $list = "{list ";

    foreach my $tweet (@$tl) {
      my $text = "@" . $tweet->{user}{screen_name} . ": " . $tweet->{text};
      $list .= "{listitem text:" . stfl::quote($text) . "}";
	}

	$list .= "}";
	return $list;
}

